package pm.workout.helper.domain.exception;

public enum DomainError {
    USER_NOT_EXISTS_ERROR,
    INVALID_INPUT_ERROR,
    SERVER_ERROR,
    USERNAME_EXISTS_ERROR,
    EMAIL_EXISTS_ERROR,
    INVALID_REQUEST_ERROR,
    USER_EXISTS_ERROR,
    INVALID_AUTHORIZATION_TOKEN,
    TRAINING_PLAN_NOT_EXISTS,
    USER_NOT_EXISTS_IN_PLAN_USERS
}
